---
- name: install kerberos client packages
  yum:
    name: ['krb5-workstation'] # for auto kinit on ssh login,'pam_krb5','krb5-libs'
    state: present

- name: copy config files
  copy:
    src: krb.conf
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644

- name: create a principal entires on client
  shell: kadmin -p {{ kadmin_user }} -w {{ kadmin_pass }} -q "addprinc -randkey  -kvno 3 {{ item }}"
  with_items:
   - host/standby.otus.test@OTUS.TEST
   - postgres/standby.otus.test@OTUS.TEST

- name: add entires to keytab on client
  shell: kadmin -p {{ kadmin_user }} -w {{ kadmin_pass }} -q "ktadd {{ item }}"
  with_items:
   - host/standby.otus.test
   - postgres/standby.otus.test

- name: obtain kerberos ticket for root
  shell: echo "{{ kadmin_pass }}" | kinit -p {{ kadmin_user }}

...
