---
- name: install nfs server packages
  yum:
    name: ['nfs-utils','autofs']
    state: present

- name: enable and start nfs client
  service:
    name: nfs-client.target
    enabled: true
    state: restarted

- name: autofs config step 2
  copy:
    src: "{{ item }}"
    dest: /etc
  with_fileglob:
    - auto.nfs
    - auto.master

- name: automount service enabled and started
  service:
    name: autofs
    enabled: true
    state: restarted

...
