---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: Install epel-relese
    yum:
      name: epel-release
      state: present
  - name: setup locale
    copy:
      src: locale.conf
      dest: /etc/locale.conf
      owner: root
      group: root
      mode: 0644
  - name: setup locale
    copy:
      src: environment
      dest: /etc/environment
      owner: root
      group: root
      mode: 0644
  - name: say Network Manager do NOT touch resolv.conf
    copy:
      src: roles/dns/files/NetworkManager.conf
      dest: /etc/NetworkManager/NetworkManager.conf
      owner: root
      group: root
      mode: 0644
  - name: reload config NetworkManager
    service:
      name: NetworkManager
      daemon_reload: yes

- hosts: primary
  become: yes
  gather_facts: no
  roles:
    - { role: dns }
    - { role: ntp }
    - { role: kerberos }
    - { role: nfs4 }
    - { role: pgsql11-primary }
- hosts: standby
  become: yes
  gather_facts: no
  tasks:
  - name: copy resolv.conf to client
    copy:
      src: roles/dns/files/resolv.conf
      dest: /etc/resolv.conf
      owner: root
      group: root
      mode: 0644
- hosts: standby
  become: yes
  gather_facts: no
  roles:
    - { role: ntp-client }
    - { role: kerberos-client }
    - { role: nfs4-client }
    - { role: pgsql11-standby }
...
